[package]
name = "tibia"
version = "0.1.0"
edition = "2021"
default-run = "tibia"

[dependencies]
base64 = "0.22"
lru = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
sha1 = "0.10"
